```properties id="b4s0qz"
spring.application.name=Pessoa_JWT

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/pessoa_jwt
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
api.security.token.secret=segredo-super-secreto-jwt
```
